### ISSUE TITLE
关于AgentWeb

### ISSUE THREAD

**Issue by Corey3213** [hnty545/hopevue-quickstart#1]
有一个
2 #1 pc 0043bd6b /system/lib/libwebviewchromium.so [armeabi-v7a]
3 #2 pc 00499a47 /system/lib/libwebviewchromium.so [armeabi-v7a]
4 #3 pc 0049d4f9 /system/lib/libwebviewchromium.so [armeabi-v7a]
5 #4 pc 00496d6b /system/lib/libwebviewchromium.so [armeabi-v7a]
6 #5 pc 00492ea7 /system/lib/libwebviewchromium.so [armeabi-v7a]
7 #6 pc 00fb2b65 /system/lib/libwebviewchromium.so [armeabi-v7a]
8 #7 pc 00fb29d3 /system/lib/libwebviewchromium.so [armeabi-v7a]
9 #8 pc 00239967 /system/lib/libwebviewchromium.so [armeabi-v7a]
10 #9 pc 0021c56d /system/lib/libwebviewchromium.so [armeabi-v7a]
11 #10 pc 0021d969 /system/lib/libwebviewchromium.so [armeabi-v7a]
12 #11 pc 0021dd43 /system/lib/libwebviewchromium.so [armeabi-v7a]
13 #12 pc 00234813 /system/lib/libwebviewchromium.so (Java_com_android_org_chromium_base_SystemMessageHandler_nativeDoRunLoopOnce+18) [armeabi-v7a]
14 #13 pc 0001ab43 /system/app/webview/arm/webview.odex (oatdata+105283) [armeabi]
15 java:
16 com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
17 android.os.Handler.dispatchMessage(Handler.java:102)
18 android.os.Looper.loop(Looper.java:135)
19 android.app.ActivityThread.main(ActivityThread.java:5413)
20 java.lang.reflect.Method.invoke(Native Method)
21 java.lang.reflect.Method.invoke(Method.java:372)
22 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
23 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)
，我看你问过这个问题，请问最后是怎么解的？线上这个崩溃比较多

**Comment by hnty545** [comment]
最后我也没解决的，你得去agentweb去提的
